const philosophers = [
  {
    id: 1,
    name: 'René Descartes',
    photo:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Frans_Hals_-_Portret_van_Ren%C3%A9_Descartes.jpg/800px-Frans_Hals_-_Portret_van_Ren%C3%A9_Descartes.jpg',
    born_date: '1596-03-31',
    death_date: '1650-02-11',
    nationality: 'French',
    era: '17th-century philosophy',
    school: [
      'Rationalism',
      'Cartesianism',
      'Mechanism',
      'Augustinianism',
      'Foundationalism',
    ],
    ideas: [
      'I think, therefore I am',
      'It is not enough to have a good mind; the main thing is to use it well.',
      'The greatest minds are capable of the greatest vices as well as of the greatest virtues.',
      'The reading of all good books is like a conversation with the finest minds of past centuries.',
      'Divide each difficulty into as many parts as is feasible and necessary to resolve it.',
      'Each problem that I solved became a rule, which served afterwards to solve other problems.',
      'If you would be a real seeker after truth, it is necessary that at least once in your life you doubt, as far as possible, all things',
      'Perfect numbers like perfect men are very rare.',
      'Everything is self-evident',
      'Except our own thoughts, there is nothing absolutely in our power',
      'When it is not in our power to follow what is true, we ought to follow what is most probable',
    ],
    books: [
      "Discourse on the Method of Rightly Conducting One's Reason and of Seeking Truth in the Sciences",
    ],
  },
  {
    id: 2,
    name: 'Immanuel Kant',
    photo:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Kant_gemaelde_3.jpg/459px-Kant_gemaelde_3.jpg',
    born_date: '1724-04-22',
    death_date: '1804-02-12',
    nationality: 'German',
    era: 'Age of Enlightenment',
    school: ['Kantianism', 'Transcendental idealism', 'Classical liberalism'],
    ideas: [
      'He who is cruel to animals becomes hard also in his dealings with men. We can judge the heart of a man by his treatment of animals.',
      'Happiness is not an ideal of reason, but of imagination.',
      'Science is organized knowledge. Wisdom is organized life.',
      'Live your life as though your every act were to become a universal law.',
      'Thoughts without content are empty, intuitions without concepts are blind.',
      'Give me matter, and I will construct a world out of it!',
      'Experience without theory is blind, but theory without experience is mere intellectual play.',
      'Ingratitude is the essence of vileness.',
      'I had therefore to remove knowledge, in order to make room for belief.',
      'What can I know? What ought I to do? What can I hope?',
      'We are not rich by what we possess but by what we can do without.',
      'How then is perfection to be sought? Wherein lies our hope? In education, and in nothing else.',
      'All our knowledge begins with the senses, proceeds then to the understanding, and ends with reason. There is nothing higher than reason.',
      'There is something splendid about innocence; but what is bad about it, in turn, is that it cannot protect itself very well and is easily seduced.',
      'One who makes himself a worm cannot complain afterwards if people step on him.',
      'The busier we are, the more acutely we feel that we live, the more conscious we are of life.',
      'Genius is the ability to independently arrive at and understand concepts that would normally have to be taught by another person.',
      'Man must be disciplined, for he is by nature raw and wild…',
      'An action, to have moral worth, must be done from duty.',
      'Whereas the beautiful is limited, the sublime is limitless, so that the mind in the presence of the sublime, attempting to imagine what it cannot, has pain in the failure but pleasure in contemplating the immensity of the attempt.',
      'Morality is not properly the doctrine of how we may make ourselves happy, but how we may make ourselves worthy of happiness.',
      'For peace to reign on Earth, humans must evolve into new beings who have learned to see the whole first',
      'Only he who, himself enlightened, is not afraid of shadows.',
      'Space and time are the framework within which the mind is constrained to construct its experience of reality.',
      'Enlightenment is man’s emergence from his self-imposed immaturity. Immaturity is the inability to use one’s understanding without guidance from another.',
      'By a lie a man throws away and as it were annihilates his dignity as a man.',
    ],
    books: [],
  },
  {
    id: 3,
    name: 'Gottfried Wilhelm Leibniz',
    photo:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Christoph_Bernhard_Francke_-_Bildnis_des_Philosophen_Leibniz_%28ca._1695%29.jpg/486px-Christoph_Bernhard_Francke_-_Bildnis_des_Philosophen_Leibniz_%28ca._1695%29.jpg',
    born_date: '1646-06-21',
    death_date: '1716-11-14',
    nationality: 'German',
    era: '17th-18th Century Philosophy',
    school: ['Rationalism', 'Optimism', 'Conceptualism', 'Foundationalism'],
    ideas: [
      'The means of obtaining as much variety as possible, but with the greatest possible order...is the means of obtaining as much perfection as possible',
      'it is the knowledge of necessary and eternal truths that distinguishes us from the mere animals and gives us Reason and the sciences, raising us to the knowledge of ourselves and of God',
      'He who does not act does not exist',
      'Perceptions which are at present insensible may grow some day: nothing is useless, and eternity provides great scope for change',
      'This is the best of all possible worlds.',
      "He who hasn't tasted bitter things hasn't earned sweet things",
      'There is nothing without a reason',
      'Music is the hidden arithmetical exercise of a mind unconscious that it is calculating',
      'There is nothing in the understanding which has not come from the senses, except the understanding itself, or the one who understands',
      'The present is big with the future',
      'Why is there something rather than nothing?',
      'Nothing is in the intellect that was not first in the senses, except the intellect itself',
      'Nothing is necessitated whose opposite is possible',
      'It is unworthy of excellent men to lose hours like slaves in the labour of calculation which could safely be relegated to anyone else if machines were used',
      'If you could blow the brain up to the size of a mill and walk about inside, you would not find consciousness',
      'For all bodies are in perpetual flux like rivers, and parts are passing in and out of them continually',
      'This interconnection or accommodation of all created things to each other, and each to all the others, brings it about that each simple substance has relations that express all the others, and consequently, that each simple substance is a perpetual, living mirror of the universe',
      'It is true that the more we see some connection in what happens to us, the more we are confirmed in the opinion we have about the reality of our appearances; and it is also true that the more we examine our appearances closely, the more we find them well-sequenced, as microscopes and other aids in making experiments have shown us',
      'Imaginary numbers are a fine and wonderful resource of the divine intellect, almost an amphibian between being and non-being',
      'The mind is not only capable of knowing [innate ideas], but further of finding them in itself; and if it had only the simple capacity to receive knowledge…it would not be the source of necessary truths…',
      'I have so many ideas that may perhaps be of some use in time if others more penetrating than I go deeply into them someday and join the beauty of their minds to the labour of mine',
      'The mind leans on [innate] principles every moment, but it does not come so easily to distinguish them and to represent them distinctly and separately, because that demands great attention to its acts, and the majority of people, little accustomed to think, has little of it.',
      'For I hold that it is only when we can prove everything we assert that we understand perfectly the thing under consideration',
      'For the [innate] general principles enter into our thoughts, of which they form the soul and the connection. They are as necessary thereto as the muscles and sinews are for walking, although we do not at all think of them',
    ],
    books: [],
  },
  {
    id: 4,
    name: 'Arthur Schopenhauer',
    photo:
      'https://upload.wikimedia.org/wikipedia/commons/b/bc/Arthur_Schopenhauer_by_J_Sch%C3%A4fer%2C_1859b.jpg',
    born_date: '1788-02-22',
    death_date: '1860-07-21',
    nationality: 'German',
    era: '19th Century Philosophy',
    school: [
      'Transcendental idealism',
      'Continental philosophy',
      'Philosophical pessimism',
    ],
    ideas: [
      'Talent hits a target no one else can hit. Genius hits a target no one else can see',
      'Compassion is the basis of morality',
      'A man can be himself only so long as he is alone; and if he does not love solitude, he will not love freedom; for it is only when he is alone that he is really free',
      'Mostly it is loss which teaches us about the worth of things',
      'The assumption that animals are without rights and the illusion that our treatment of them has no moral significance is a positively outrageous example of Western crudity and barbarity. Universal compassion is the only guarantee of morality',
      'Every man takes the limits of his own field of vision for the limits of the world',
      'Happiness consists in frequent repetition of pleasure',
      'The person who writes for fools is always sure of a large audience',
      'It is difficult to find happiness within oneself, but it is impossible to find it anywhere else',
      'They tell us that Suicide is the greatest piece of Cowardice... That Suicide is wrong; when it is quite obvious that there is nothing in this world to which every man has a more unassailable title than to his own life and person',
      'Compassion for animals is intimately associated with goodness of character, and it may be confidently asserted that he who is cruel to animals cannot be a good man',
      'One should use common words to say uncommon things',
      'Every miserable fool who has nothing at all of which he can be proud, adopts as a last resource pride in the nation to which he belongs; he is ready and happy to defend all its faults and follies tooth and nail, thus reimbursing himself for his own inferiority',
      'When we read, another person thinks for us: we merely repeat his mental process. In learning to write, the pupil goes over with his pen what the teacher has outlined in pencil: so in reading; the greater part of the work of thought is already done for us. This is why it relieves us to take up a book after being occupied with our own thoughts. And in reading, the mind is, in fact, only the playground of another’s thoughts. So it comes about that if anyone spends almost the whole day in reading, and by way of relaxation devotes the intervals to some thoughtless pastime, he gradually loses the capacity for thinking; just as the man who always rides, at last forgets how to walk. This is the case with many learned persons: they have read themselves stupid',
      'Man can do what he wills but he cannot will what he wills.',
      'The art of not reading is a very important one. It consists in not taking an interest in whatever may be engaging the attention of the general public at any particular time. When some political or ecclesiastical pamphlet, or novel, or poem is making a great commotion, you should remember that he who writes for fools always finds a large public. A precondition for reading good books is not reading bad ones: for life is short',
      'Life is a constant process of dying',
      'We forfeit three-fourths of ourselves in order to be like other people',
      'A sense of humour is the only divine quality of man',
      'It is a wise thing to be polite; consequently, it is a stupid thing to be rude. To make enemies by unnecessary and willful incivility, is just as insane a proceeding as to set your house on fire. For politeness is like a counter--an avowedly false coin, with which it is foolish to be stingy',
      'We will gradually become indifferent to what goes on in the minds of other people when we acquire a knowledge of the superficial nature of their thoughts, the narrowness of their views and of the number of their errors. Whoever attaches a lot of value to the opinions of others pays them too much honor',
      'A high degree of intellect tends to make a man unsocial',
      'What disturbs and depresses young people is the hunt for happiness on the firm assumption that it must be met with in life. From this arises constantly deluded hope and so also dissatisfaction. Deceptive images of a vague happiness hover before us in our dreams, and we search in vain for their original. Much would have been gained if, through timely advice and instruction, young people could have had eradicated from their minds the erroneous notion that the world has a great deal to offer them',
      'If children were brought into the world by an act of pure reason alone, would the human race continue to exist? Would not a man rather have so much sympathy with the coming generation as to spare it the burden of existence, or at any rate not take it upon himself to impose that burden upon it in cold blood?',
      'Treat a work of art like a prince: let it speak to you first',
      'It would be better if there were nothing. Since there is more pain than pleasure on earth, every satisfaction is only transitory, creating new desires and new distresses, and the agony of the devoured animal is always far greater than the pleasure of the devourer',
      'Religion is the masterpiece of the art of animal training, for it trains people as to how they shall think',
      'Great men are like eagles, and build their nest on some lofty solitude',
      'So the problem is not so much to see what nobody has yet seen, as to think what nobody has yet thought concerning that which everybody sees',
    ],
    books: [],
  },
  {
    id: 5,
    name: 'Georg Wilhelm Friedrich Hegel',
    photo:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Hegel_by_Schlesinger.jpg/474px-Hegel_by_Schlesinger.jpg',
    born_date: '1770-08-27',
    death_date: '1831-11-14',
    nationality: 'German',
    era: '19th Century Philosophy',
    school: [
      'Conceptualism',
      'Continental philosophy',
      'German idealism',
      'Objective idealism',
      'Hegelianism',
    ],
    ideas: [
      'Nothing great in the world was accomplished without passion',
      'We learn from history that we do not learn from history',
      'To be independent of public opinion is the first formal condition of achieving anything great',
      'Genuine tragedies in the world are not conflicts between right and wrong. They are conflicts between two rights',
      'What experience and history teaches us is that people and governments have never learned anything from history, or acted on principles deduced from it',
      'Truth is found neither in the thesis nor the antithesis, but in an emergent synthesis which reconciles the two',
      'Evil resides in the very gaze which perceives Evil all around itself',
      "Only one man ever understood me, and he didn't understand me",
      'Education is the art of making man ethical',
      'It is solely by risking life that freedom is obtained; ...The individual who has not staked his or her life may, no doubt, be recognized as a Person; but he or she has not attained the truth of this recognition as an independent self-consciousness',
      'The valor that struggles is better than the weakness that endures',
      '...this is love. I have my self-consciousness not in myself but in the other. I am satisfied and have peace with myself only in this other and I AM only because I have peace with myself; if I did not have it then I would be a contradiction that falls to pieces. This other, because it likewise exists outside itself, has its self-consciousness only in me; and both the other and I are only this consciousness of being-outside-ourselves and of our identity; we are only this intuition, feeling, and knowledge of our unity. This is love, and without knowing that love is both a distinguishing and the sublation of this distinction, one speaks emptily of it',
      'When liberty is mentioned, we must always be careful to observe whether it is not really the assertion of private interests which is thereby designated',
      'The owl of Minerva begins its flight only with the coming of the dusk',
      'The bud disappears when the blossom breaks through, and we might say that the former is refuted by the latter; in the same way when the fruit comes, the blossom may be explained to be a false form of the plant’s existence, for the fruit appears as its true nature in place of the blossom. The ceaseless activity of their own inherent nature makes these stages moments of an organic unity, where they not merely do not contradict one another, but where one is as necessary as the other; and constitutes thereby the life of the whole',
      'Too fair to worship, too divine to love',
      "The ignorant man is not free, because what confronts him is an alien world, something outside him and in the offing, on which he depends, without his having made this foreign world for himself and therefore without being at home in it by himself as in something his own. The impulse of curiosity, the pressure for knowledge, from the lowest level up to the highest rung of philosophical insight arises only from the struggle to cancel this situation of unfreedom and to make the world one's own in one's ideas and thought",
      'People who are too fastidious towards the finite never reach actuality, but linger in abstraction, and their light dies away',
      'Once the state has been founded, there can no longer be any heroes. They come on the scene only in uncivilized conditions',
      "America is therefore the land of the future, where, in the ages that lie before us, the burden of the World's History shall reveal itself",
      'An idea is always a generalization, and generalization is a property of thinking. To generalize means to think',
      'If we go on to cast a look at the fate of world historical personalities... we shall find it to have been no happy one. They attained no calm enjoyment; their whole life was labor and trouble; their whole nature was nothing but their master passion. When their object is attained they fall off like empty hulls from the kernel. They die early, like Alexander; they are murdered, like Casear; transported to St. Helena, like Napoleon',
      "The state of man's mind, or the elementary phase of mind which he so far possesses, conforms precisely to the state of the world as he so far views it",
      'History is not the soil in which happiness grows. The periods of happiness in it are the blank pages of history',
      'World history is a court of judgment',
      'History in general is therefore the development of Spirit in Time, as Nature is the development of the Idea is Space',
      'If we are in a general way permitted to regard human activity in the realm of the beautiful as a liberation of the soul, as a release from constraint and restriction, in short to consider that art does actually alleviate the most overpowering and tragic catastrophes by means of the creations it offers to our contemplation and enjoyment, it is the art of music which conducts us to the final summit of that ascent to freedom',
      'The length of the journey has to be borne with, for every moment is necessary',
      'Art does not simply reveal God: it is one of the ways in which God reveals, and thus actualizes, himself',
    ],
    books: [],
  },
  {
    id: 6,
    name: 'Ludwig Andreas von Feuerbach',
    photo:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Ludwig_Andreas_Feuerbach.jpg/525px-Ludwig_Andreas_Feuerbach.jpg',
    born_date: '1804-07-28',
    death_date: '1872-09-13',
    nationality: 'German',
    era: '19th Century Philosophy',
    school: [
      'Anthropological materialism',
      'Secular humanism',
      'Young Hegelians',
    ],
    ideas: [
      'I would rather be a devil in alliance with truth, than an angel in alliance with falsehood.',
      'It is not as in the Bible, that God created man in his own image. But, on the contrary, man created God in his own image.',
      'My only wish isto transform friends of God into friends of man, believers into thinkers, devotees of prayer into devotees of work, candidates for the hereafter into students of the world, Christians who, by their own procession and admission, are half animal, half angel into persons, into whole persons.',
      'Wherever morality is based on theology, wherever the right is made dependent on divine authority, the most immoral, unjust, infamous things can be justified and established.',
      'Christianity set itself the goal of fulfilling man’s unattainable desires, but for that very reason ignored his attainable desires. By promising man eternal life, it deprived him of temporal life, by teaching him to trust in God’s help it took away his trust in his own powers; by giving him faith in a better life in heaven, it destroyed his faith in a better life on earth and his striving to attain such a life. Christianity gave man what his imagination desires, but for that very reason failed to give him what he really and truly desires.',
      'Religion is the dream of the human mind. But even in dreams we do not find ourselves in emptiness or in heaven, but on earth, in the realm of reality; we only see real things in the entrancing splendor of imagination and caprice, instead of in the simple daylight of reality and necessity.',
      'As we expand our knowledge of good books, we shrink the circle of men whose company we appreciate.',
      'The power of thought is the light of knowledge, the power of will is the energy of character, the power of heart is love. Reason, love and power of will are perfections of man.',
      'The present age ... prefers the sign to the thing signified, the copy to the original, fancy to reality, the appearance to the essence ... for in these days illusion only is sacred, truth profane.',
      'For the religious the holy is truth, for the philosophic the truth is holy',
      'The power of miracle is the power of imagination',
      'What yesterday was still religion is no longer such today; and what today is atheism, tomorrow will be religion',
      'To theology, ...only what it holds sacred is true, whereas to philosophy, only what holds true is sacred',
      'This work, though it deals only with eating and drinking, which are regarded in the eyes of our supernaturalistic mock-culture as the lowest acts, is of the greatest philosophic significance and importance... How former philosophers have broken their heads over the question of the bond between body and soul! Now we know, on scientific grounds, what the masses know from long experience, that eating and drinking hold together body and soul, that the searched-for bond is nutrition',
      'If therefore my work is negative, irreligious, atheistic, let it be remembered that atheism — at least in the sense of this work — is the secret of religion itself; that religion itself, not indeed on the surface, but fundamentally, not in intention or according to its own supposition, but in its heart, in its essence, believes in nothing else than the truth and divinity of human nature',
      'The doctrine of foods is of great ethical and political significance. Food becomes blood, blood becomes heart and brain, thoughts and mind stuff. Human fare is the foundation of human culture and thought. Would you improve a nation? Give it, instead of declamations against sin, better food. Man is what he eats',
      'Is it man that possesses love, or is it not much rather love that possesses man?',
      'I have always taken as the standard of the mode of teaching and writing, not the abstract, particular, professional philosopher, but universal man, that I have regarded man as the criterion of truth, and not this or that founder of a system, and have from the first placed the highest excellence of the philosopher in this, that he abstains, both as a man and as an author, from the ostentation of philosophy, i. e., that he is a philosopher only in reality, not formally, that he is a quiet philosopher, not a loud and still less a brawling one',
      "The first and highest law must be the love of man to man. Homo homini Deus est - this is the supreme practical maxim, this is the turning point of the world's History",
      "Faith is essentially intolerant ... essentially because necessarily bound up with faith is the illusion that one's cause is also God's cause",
      'Only he is a truly ethical, a truly human being, who has the courage to see through his own religious feelings and needs',
      'The history of philosophical system is the picture gallery of reason',
      'To prove cannot mean anything other than to bring the other person to my own conviction. The truth lies only in the unification of “I” and “You.” The Other of pure thought, however, is the sensuous intellect in general. In the field of philosophy, proof therefore consists only in the fact that the contradiction between sensuous intellect and pure thought is disposed, so that thought is true not only for itself but also for its opposite',
    ],
    books: [],
  },
  {
    id: 7,
    name: 'Søren Aabye Kierkegaard',
    photo:
      'https://upload.wikimedia.org/wikipedia/commons/d/d4/S%C3%B8ren_Kierkegaard_%281813-1855%29_-_%28cropped%29.jpg',
    born_date: '1813-05-05',
    death_date: '1855-11-11',
    nationality: 'Danish',
    era: '19th Century Philosophy',
    school: ['Continental philosophy', 'Existentialism'],
    ideas: [
      'Life can only be understood backwards; but it must be lived forwards',
      'The function of prayer is not to influence God, but rather to change the nature of the one who prays',
      'People demand freedom of speech as a compensation for the freedom of thought which they seldom use',
      'Anxiety is the dizziness of freedom',
      "People understand me so poorly that they don't even understand my complaint about them not understanding me",
      'Life is not a problem to be solved, but a reality to be experienced',
      "There are two ways to be fooled. One is to believe what isn't true; the other is to refuse to believe what is true",
      'The most common form of despair is not being who you are',
      'The greatest hazard of all, losing one’s self, can occur very quietly in the world, as if it were nothing at all. No other loss can occur so quietly; any other loss - an arm, a leg, five dollars, a wife, etc. - is sure to be noticed',
      'I see it all perfectly; there are two possible situations — one can either do this or that. My honest opinion and my friendly advice is this: do it or do not do it — you will regret both',
      'What labels me, negates me',
      "The most painful state of being is remembering the future, particularly the one you'll never have",
      'The Bible is very easy to understand. But we Christians are a bunch of scheming swindlers. We pretend to be unable to understand it because we know very well that the minute we understand, we are obliged to act accordingly',
      'In addition to my other numerous acquaintances, I have one more intimate confidant… My depression is the most faithful mistress I have known — no wonder, then, that I return the love',
      'Marry, and you will regret it; don’t marry, you will also regret it; marry or don’t marry, you will regret it either way. Laugh at the world’s foolishness, you will regret it; weep over it, you will regret that too; laugh at the world’s foolishness or weep over it, you will regret both. Believe a woman, you will regret it; believe her not, you will also regret it… Hang yourself, you will regret it; do not hang yourself, and you will regret that too; hang yourself or don’t hang yourself, you’ll regret it either way; whether you hang yourself or do not hang yourself, you will regret both. This, gentlemen, is the essence of all philosophy',
      "What is a poet? An unhappy man who hides deep anguish in his heart, but whose lips are so formed that when the sigh and cry pass through them, it sounds like lovely music.... And people flock around the poet and say: 'Sing again soon' - that is, 'May new sufferings torment your soul but your lips be fashioned as before, for the cry would only frighten us, but the music, that is blissful",
      'Love is the expression of the one who loves, not of the one who is loved. Those who think they can love only the people they prefer do not love at all. Love discovers truths about individuals that others cannot see',
      "A fire broke out backstage in a theatre. The clown came out to warn the public; they thought it was a joke and applauded. He repeated it; the acclaim was even greater. I think that's just how the world will come to an end: to general applause from wits who believe it's a joke",
      'What if everything in the world were a misunderstanding, what if laughter were really tears?',
      'If I were to wish for anything, I should not wish for wealth and power, but for the passionate sense of the potential, for the eye which, ever young and ardent, sees the possible. Pleasure disappoints, possibility never. And what wine is so sparkling, what so fragrant, what so intoxicating, as possibility!',
      "To dare is to lose one's footing momentarily. Not to dare is to lose oneself",
      'The tyrant dies and his rule is over, the martyr dies and his rule begins',
      "To venture causes anxiety, but not to venture is to lose one's self.... And to venture in the highest is precisely to be conscious of one's self",
      'Face the facts of being what you are, for that is what changes what you are',
      'God creates out of nothing. Wonderful you say. Yes, to be sure, but he does what is still more wonderful: he makes saints out of sinners',
      'To cheat oneself out of love is the most terrible deception; it is an eternal loss for which there is no reparation, either in time or in eternity',
      'If anyone on the verge of action should judge himself according to the outcome, he would never begin',
      'The proud person always wants to do the right thing, the great thing. But because he wants to do it in his own strength, he is fighting not with man, but with God',
    ],
    books: [],
  },
  {
    id: 8,
    name: 'Martin Heidegger',
    photo:
      'https://upload.wikimedia.org/wikipedia/commons/6/64/Heidegger_2_%281960%29.jpg',
    born_date: '1889-09-26',
    death_date: '1976-05-26',
    nationality: 'German',
    era: '20th Century Philosophy',
    school: [
      'Continental philosophy',
      'Existentialism',
      'Phenomenology',
      'Hermeneutics',
    ],
    ideas: [
      "Tell me how you read and I'll tell you who you are",
      "Anyone can achieve their fullest potential, who we are might be predetermined, but the path we follow is always of our own choosing. We should never allow our fears or the expectations of others to set the frontiers of our destiny. Your destiny can't be changed but, it can be challenged. Every man is born as many men and dies as a single one",
      'If I take death into my life, acknowledge it, and face it squarely, I will free myself from the anxiety of death and the pettiness of life - and only then will I be free to become myself',
      'Why is love beyond all measure of other human possibilities so rich and such a sweet burden for the one who has been struck by it? Because we change ourselves into that which we love, and yet remain ourselves. Then we would like to thank the beloved, but find nothing that would do it adequately. We can only be thankful to ourselves. Love transforms gratitude into faithfulness to ourselves and into an unconditional faith in the Other. Thus love steadily expands its most intimate secret. Closeness here is existence in the greatest distance from the other- the distance that allows nothing to dissolve - but rather presents the “thou” in the transparent, but “incomprehensible” revelation of the “just there”. That the presence of the other breaks into our own life - this is what no feeling can fully encompass. Human fate gives itself to human fate, and it is the task of pure love to keep this self-surrender as vital as on the first day',
      'Man acts as though he were the shaper and master of language, while in fact language remains the master of man',
      'Everyone is the other and no one is himself',
      'Thinking only begins at the point where we have come to know that Reason, glorified for centuries, is the most obstinate adversary of thinking',
      'Only he who already understands can listen',
      'The poets are in the vanguard of a changed conception of Being',
      'And so man, as existing transcendence abounding in and surpassing toward possibilities, is a creature of distance. Only through the primordial distances he establishes toward all being in his transcendence does a true nearness to things flourish in him',
    ],
    books: [],
  },
  {
    id: 9,
    name: 'Aldous Leonard Huxley',
    photo:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Aldous_Huxley_psychical_researcher.png/450px-Aldous_Huxley_psychical_researcher.png',
    born_date: '1894-07-26',
    death_date: '1963-11-22',
    nationality: 'English',
    era: '20th Century Philosophy',
    school: ['Perennialism'],
    ideas: [
      'Facts do not cease to exist because they are ignored',
      'Words can be like X-rays if you use them properly -- they’ll go through anything. You read and you’re pierced',
      'After silence, that which comes nearest to expressing the inexpressible is music',
      "But I don't want comfort. I want God, I want poetry, I want real danger, I want freedom, I want goodness. I want sin",
      'You shall know the truth and the truth shall make you mad',
      'Maybe this world is another planet’s hell',
      "Actual happiness always looks pretty squalid in comparison with the overcompensations for misery. And, of course, stability isn't nearly so spectacular as instability. And being contented has none of the glamour of a good fight against misfortune, none of the picturesqueness of a struggle with temptation, or a fatal overthrow by passion or doubt. Happiness is never grand",
      'The more powerful and original a mind, the more it will incline towards the religion of solitude',
      "If one's different, one's bound to be lonely",
      'I want to know what passion is. I want to feel something strongly',
      'The real hopeless victims of mental illness are to be found among those who appear to be most normal. "Many of them are normal because they are so well adjusted to our mode of existence, because their human voice has been silenced so early in their lives, that they do not even struggle or suffer or develop symptoms as the neurotic does." They are normal not in what may be called the absolute sense of the word; they are normal only in relation to a profoundly abnormal society. Their perfect adjustment to that abnormal society is a measure of their mental sickness. These millions of abnormally normal people, living without fuss in a society to which, if they were fully human beings, they ought not to be adjusted',
      'I wanted to change the world. But I have found that the only thing one can be sure of changing is oneself',
      'An intellectual is a person who has discovered something more interesting than sex',
      'One believes things because one has been conditioned to believe them',
      'There are things known and there are things unknown, and in between are the doors of perception',
      'That men do not learn very much from the lessons of history is the most important of all the lessons that history has to teach',
      "I am I, and I wish I weren't",
      'It’s dark because you are trying too hard.\r\nLightly child, lightly. Learn to do everything lightly.\r\nYes, feel lightly even though you’re feeling deeply.\r\nJust lightly let things happen and lightly cope with them.\r\n\r\nI was so preposterously serious in those days, such a humorless little prig.\r\nLightly, lightly – it’s the best advice ever given me.\r\nWhen it comes to dying even. Nothing ponderous, or portentous, or emphatic.\r\nNo rhetoric, no tremolos,\r\nno self conscious persona putting on its celebrated imitation of Christ or Little Nell.\r\nAnd of course, no theology, no metaphysics.\r\nJust the fact of dying and the fact of the clear light.\r\n\r\nSo throw away your baggage and go forward.\r\nThere are quicksands all about you, sucking at your feet,\r\ntrying to suck you down into fear and self-pity and despair.\r\nThat’s why you must walk so lightly.\r\nLightly my darling,\r\non tiptoes and no luggage,\r\nnot even a sponge bag,\r\ncompletely unencumbered',
      'The secret of genius is to carry the spirit of the child into old age, which means never losing your enthusiasm',
      'Chronic remorse, as all the moralists are agreed, is a most undesirable sentiment. If you have behaved badly, repent, make what amends you can and address yourself to the task of behaving better next time. On no account brood over your wrongdoing. Rolling in the muck is not the best way of getting clean',
      'Experience is not what happens to a man; it is what a man does with what happens to him',
      'Most human beings have an almost infinite capacity for taking things for granted',
      '...most men and women will grow up to love their servitude and will never dream of revolution',
      "Every man's memory is his private literature",
      'We live together, we act on, and react to, one another; but always and in all circumstances we are by ourselves. The martyrs go hand in hand into the arena; they are crucified alone. Embraced, the lovers desperately try to fuse their insulated ecstasies into a single self-transcendence; in vain. By its very nature every embodied spirit is doomed to suffer and enjoy in solitude. Sensations, feelings, insights, fancies—all these are private and, except through symbols and at second hand, incommunicable. We can pool information about experiences, but never the experiences themselves. From family to nation, every human group is a society of island universes',
      'Happiness is not achieved by the conscious pursuit of happiness; it is generally the by-product of other activities',
      'All that happens means something; nothing you do is ever insignificant',
      'Consistency is contrary to nature, contrary to life. The only completely consistent people are the dead',
      "There is only one corner of the universe you can be certain of improving, and that's your own self",
      'No social stability without individual stability',
      'To travel is to discover that everyone is wrong about other countries',
      'That all men are equal is a proposition which at ordinary times no sane individual has ever given his assent',
      'I ate civilization. It poisoned me; I was defiled. And then," he added in a lower tone, "I ate my own wickedness',
      'Man is so intelligent that he feels impelled to invent theories to account for what happens in the world. Unfortunately, he is not quite intelligent enough, in most cases, to find correct explanations. So that when he acts on his theories, he behaves very often like a lunatic',
      'Ironically enough, the only people who can hold up indefinitely under the stress of modern war are psychotics. Individual insanity is immune to the consequences of collective insanity',
      'Every man with a little leisure and enough money for railway tickets, every man, indeed, who knows how to read, has it in his power to magnify himself, to multiply the ways in which he exists, to make his life full, significant and interesting',
      'A really efficient totalitarian state would be one in which the all-powerful executive of political bosses and their army of managers control a population of slaves who do not have to be coerced, because they love their servitude',
      "The propagandist's purpose is to make one set of people forget that certain other sets of people are human",
      'For in spite of language, in spite of intelligence and intuition and sympathy, one can never really communicate anything to anybody',
      'The man who comes back through the Door in the Wall will never be quite the same as the man who went out. He will be wiser but less sure, happier but less self-satisfied, humbler in acknowledging his ignorance yet better equipped to understand the relationship of words to things, of systematic reasoning to the unfathomable mystery which it tries, forever vainly, to comprehend',
      "Armaments, universal debt, and planned obsolescence—those are the three pillars of Western prosperity. If war, waste, and moneylenders were abolished, you'd collapse. And while you people are overconsuming the rest of the world sinks more and more deeply into chronic disaster",
      'Experience teaches only the teachable',
      'Technological progress has merely provided us with more efficient means for going backwards',
      'Great is truth, but still greater, from a practical point of view, is silence about truth',
      'To his dog, every man is Napoleon; hence the constant popularity of dogs',
      'A love of nature keeps no factories busy',
      "It is a bit embarrassing to have been concerned with the human problem all one's life and find at the end that one has no more to offer by way of advice than 'Try to be a little kinder",
      "I'm afraid of losing my obscurity. Genuineness only thrives in the dark. Like celery",
      'Deprived of their newspapers or a novel, reading-addicts will fall back onto cookery books, on the literature which is wrapped around bottles of patent medicine, on those instructions for keeping the contents crisp which are printed on the outside of boxes of breakfast cereals. On anything',
      "It is natural to believe in God when you're alone-- quite alone, in the night, thinking about death",
      "It isn't a matter of forgetting. What one has to learn is how to remember and yet be free of the past",
      'Pain was a fascinating horror',
      'We cannot reason ourselves out of our basic irrationality. All we can do is learn the art of being irrational in a reasonable way',
      "The leech's kiss, the squid's embrace,\r\nThe prurient ape's defiling touch:\r\nAnd do you like the human race?\r\nNo, not much",
      'All gods are homemade, and it is we who pull their strings, and so, give them the power to pull ours',
      'The vast majority of human beings dislike and even actually dread all notions with which they are not familiar... Hence it comes about that at their first appearance innovators have generally been persecuted, and always derided as fools and madmen',
      'The trouble with fiction," said John Rivers, "is that it makes too much sense. Reality never makes sense',
      'It is only when we have renounced our preoccupation with "I," "me," "mine," that we can truly possess the world in which we live. Everything, provided that we regard nothing as property. And not only is everything ours; it is also everybody else\'s',
      "Did you ever feel, as though you had something inside you that was only waiting for you to give it a chance to come out? Some sort of extra power that you aren't using - you know, like all the water that goes down the falls instead of through the turbines?",
      'The Bhagavad-Gita is the most systematic statement of spiritual evolution of endowing value to mankind. It is one of the most clear and comprehensive summaries of perennial philosophy ever revealed; hence its enduring value is subject not only to India but to all of humanity',
      "Don't try to behave as though you were essentially sane and naturally good. We're all demented sinners in the same cosmic boat - and the boat is perpetually sinking",
      'Consciousness is only possible through change; change is only possible through movement',
      'There will be in the next generation or so a pharmacological method of making people love their servitude and producing dictatorship without tears, so to speak, producing a kind of painless concentration camp for entire societies so that people will in fact have their liberties taken away from them but will rather enjoy it',
      "I'm claiming the right to be unhappy",
      "In a properly organized society like ours, nobody has any opportunities for being noble or heroic. Conditions have got to be thoroughly unstable before the occasion can arise. When there are wars, where there are divided allegiances, where there are temptations to be resisted, objects of love to be fought for or defended - there, obviously, nobility and heroism have some sense. But there aren't any wars nowadays. The greatest care is taken to prevent you from loving anyone too much. There's no such thing as a divided allegiance; you're so conditioned that you can't help doing what you ought to do. And what you ought to do is on the whole so pleasant, so many of the natural impulses are allowed free play, that there really aren't any temptations to resist. And if ever, by some unlucky chance, anything unpleasant should somehow happen, why, there's always soma to give you a holiday from the facts. And there's always soma to calm your anger, to reconcile you to your enemies, to make you patient and long-suffering. In the past you could only accomplish these things by making a great effort and after years of hard moral training. now, you swallow two or three half-gramme tablets, and there you are. Anybody can be virtuous now. You can carry at least half your mortality about in a bottle. Christianity without tears - that's what soma is",
      'The charm of history and its enigmatic lesson consist in the fact that, from age to age, nothing changes and yet everything is completely different',
      "Human beings act in a great variety of irrational ways, but all of them seem to be capable, if given a fair chance, of making a reasonable choice in the light of available evidence. Democratic institutions can be made to work only if all concerned do their best to impart knowledge and to encourage rationality. But today, in the world's most powerful democracy, the politicians and the propagandists prefer to make nonsense of democratic procedures by appealing almost exclusively to the ignorance and irrationality of the electors",
      'When people are suspicious with you, you start being suspicious with them',
      'My father considered a walk among the mountains as the equivalent of churchgoing',
      'To be enlightened is to be aware, always, of total reality in its immanent otherness - to be aware of it and yet remain in a condition to survive as an animal. Our goal is to discover that we have always been where we ought to be. Unhappily we make the task exceedingly difficult for ourselves',
      'So long as men worship the Caesars and Napoleons, Caesars and Napoleons will duly rise and make them miserable',
      'Each person is at each moment capable of remembering all that has ever happened to him and of perceiving everything that is happening everywhere in the universe',
      'It isn’t only art that is incompatible with happiness, it’s also science. Science is dangerous, we have to keep it most carefully chained and muzzled',
      "A bad book is as much of a labor to write as a good one; it comes as sincerely from the author's soul",
    ],
    books: [],
  },
  {
    id: 10,
    name: 'Johann Wolfgang von Goethe',
    photo:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Goethe_%28Stieler_1828%29.jpg/486px-Goethe_%28Stieler_1828%29.jpg',
    born_date: '1749-08-28',
    death_date: '1832-03-22',
    nationality: 'German',
    era: '18th Century Philosophy',
    school: ['Neo-Spinozism'],
    ideas: [
      'One ought, every day at least, to hear a little song, read a good poem, see a fine picture, and, if it were possible, to speak a few reasonable words.',
      'If you treat an individual as he is, he will remain how he is. But if you treat him as if he were what he ought to be and could be, he will become what he ought to be and could be.',
      'We do not have to visit a madhouse to find disordered minds; our planet is the mental institution of the universe.',
      'I have possessed that heart, that noble soul, in whose presence I seemed to be more than I really was, because I was all that I could be.',
      'If I love you, what business is it of yours?',
      'A man sees in the world what he carries in his heart.',
      'There is nothing more frightful than ignorance in action.',
      'Daring ideas are like chessmen moved forward. They may be beaten, but they may start a winning game.',
      'As soon as you trust yourself, you will know how to live.',
      'You can easily judge the character of a man by how he treats those who can do nothing for him.',
      'I bid the chords sweet music make,\r\nAnd all must follow in my wake.',
      "Nothing shows a man's character more than what he laughs at.",
      'A person hears only what they understand.',
      'Things which matter most must never be at the mercy of things which matter least.',
      'Magic is believing in yourself, if you can do that, you can make anything happen.',
      'The human race is a monotonous affair. Most people spend the greatest part of their time working in order to live, and what little freedom remains so fills them with fear that they seek out any and every means to be rid of it.',
      "If you've never eaten while crying you don t know what life tastes like.",
      'To think is easy. To act is hard. But the hardest thing in the world is to act in accordance with your thinking.',
      'None are more hopelessly enslaved than those who falsely believe they are free.',
      'By seeking and blundering we learn.',
      'There is nothing worse than aggressive stupidity.',
      'I love those who yearn for the impossible.',
      'The person born with a talent they are meant to use will find their greatest happiness in using it.',
      'The greatest thing in this world is not so much where we stand as in what direction we are moving.',
      'Age does not make us childish, as some say; it finds us true children.',
      'The soul that sees beauty may sometimes walk alone.',
      'Music is liquid architecture; Architecture is frozen music.',
      'Those who know nothing of foreign languages know nothing of their own.',
      'If God had wanted me otherwise, He would have created me otherwise.',
      'At the moment of commitment the entire universe conspires to assist you.',
      'Knowing is not enough; we must apply. Willing is not enough; we must do.',
      'Life belongs to the living, and he who lives must be prepared for changes.',
      'All the knowledge I possess everyone else can acquire, but my heart is all my own.',
      'Everything is hard before it is easy',
      'We are shaped and fashioned by what we love.',
      'Who are you then? I am part of that power which eternally wills evil and eternally works good.',
      'We must always change, renew, rejuvenate ourselves; otherwise, we harden.',
      'You can’t, if you can’t feel it, if it never\r\nRises from the soul, and sways\r\nThe heart of every single hearer,\r\nWith deepest power, in simple ways.\r\nYou’ll sit forever, gluing things together,\r\nCooking up a stew from other’s scraps,\r\nBlowing on a miserable fire,\r\nMade from your heap of dying ash.\r\nLet apes and children praise your art,\r\nIf their admiration’s to your taste,\r\nBut you’ll never speak from heart to heart,\r\nUnless it rises up from your heart’s space.',
      'We are our own devils; we drive ourselves out of our Edens.',
      'There is strong shadow where there is much light.',
      'Divide and rule, a sound motto. Unite and lead, a better one.',
      'This is the true measure of love: when we believe that we alone can love, that no one could ever have loved so before us, and that no one will ever love in the same way after us.',
      "Sometimes I don't understand how another can love her, is allowed to love her, since I love her so completely myself, so intensely, so fully, grasp nothing, know nothing, have nothing but her!",
      'All truly wise thoughts have been thought already thousands of times; but to make them truly ours, we must think them over again honestly, until they take root in our personal experience.',
      'Talent develops in solitude, character develops in the stream of life.',
      'God help us -- for art is long, and life so short.',
      "If you don't feel it, you'll never get it.",
      "It's true that nothing in this world makes us so necessary to others as the affection we have for them.",
      'People who think honestly and deeply have a hostile attitude towards the public.',
      'Love is an ideal thing, marriage a real thing; a confusion of the real with the ideal never goes unpunished.',
      'It is not doing the thing we like to do, but liking the thing we have to do, that makes life blessed.',
      'What you get by achieving your goals is not as important as what you become by achieving your goals.',
      "Tell a wise person, or else keep silent,\r\nbecause the mass man will mock it right away.\r\nI praise what is truly alive,\r\nwhat longs to be burned to death.\r\n\r\nIn the calm water of the love-nights,\r\nwhere you were begotten, where you have begotten,\r\na strange feeling comes over you,\r\nwhen you see the silent candle burning.\r\n\r\nNow you are no longer caught\r\nin the obsession with darkness,\r\nand a desire for higher love-making\r\nsweeps you upward.\r\n\r\nDistance does not make you falter.\r\nNow, arriving in magic, flying,\r\nand finally, insane for the light,\r\nyou are the butterfly and you are gone.\r\n\r\nAnd so long as you haven't experienced\r\nthis: to die and so to grow,\r\nyou are only a troubled guest\r\non the dark earth.",
      'Is this the destiny of man? Is he only happy before he has acquired his reason or after he has lost it?',
      'Love does not dominate; it cultivates.',
      'Remember to live.',
      "One never goes so far as when one doesn't know where one is going.",
      'Here too it’s masquerade, I find:\r\nAs everywhere, the dance of mind.\r\nI grasped a lovely masked procession,\r\nAnd caught things from a horror show…\r\nI’d gladly settle for a false impression,\r\nIf it would last a little longer, though.',
      'All theory is gray, my friend. But forever green is the tree of life.',
      'If you would create something, you must be something.',
      'Dream no small dreams for they have no power to move the hearts of men.',
      'Choose well. Your choice is brief, and yet endless.',
      'Difficulties increase the nearer we get to the goal.',
      'We are never deceived; we deceive ourselves.',
      'We know accurately only when we know little; doubt grows with knowledge.',
      'Leap and the net will appear.',
      'To be loved for what one is, that is the greatest exception. The great majority love in others only what they lend him; their own selves, their version of him.',
      'Every reader, if he has a strong mind, reads himself into the book, and amalgamates his thoughts with those of the author.',
      'Few people have the imagination for reality.',
      'Doubt can only be removed by action.',
      'The intelligent man finds everything laughable, the sensible man hardly anything.',
      'There is nothing more dreadful than imagination without taste.',
      'The suffering may be moral or physical; and in my opinion it is just as absurd to call a man a coward who destroys himself, as to call a man a coward who dies of a malignant fever.',
      'The greatest evil that can befall man is that he should come to think ill of himself.',
      'Whatever is the lot of humankind\r\nI want to taste within my deepest self.\r\nI want to seize the highest and the lowest,\r\nto load its woe and bliss upon my breast,\r\nand thus expand my single self titanically\r\nand in the end go down with all the rest.',
      "Once I blazed across the sky,\r\nLeaving trails of flame;\r\nI fell to earth, and here I lie -\r\nWho'll help me up again?\r\n-A Shooting Star",
      'Night is the other half of life, and the better half.',
      'Everybody wants to be somebody,but nobody wants to grow...',
      'All that is transitory is but a metaphor.',
      'I laugh at my heart, and do its will.',
      'Faust: Who holds the devil, let him hold him well,\r\nHe hardly will be caught a second time.',
      'What is uttered from the heart alone will win the heart of others to your own.',
      'The rich want good wine, the poor, plenty of wine.',
      'One can stand anything except a succession of ordinary days.',
      'We all of us live upon the past, and through the past we are destroyed.',
      'Misunderstandings and neglect occasion more mischief in the world than malice and wickedness.',
      'We often feel that we lack something, and seem to see that very quality in someone else, promptly attributing all our own qualities to him too, and a kind of ideal contentment as well. And so the happy mortal is a model of complete perfection--which we have ourselves created.',
      'There is no past we can bring back by longing for it. There is only an eternal now that builds and creates out of the past something new and better.',
      'I am not omniscient, but I know a lot.',
      'He is happiest, be he king or peasant, who finds peace in his home.',
      'Every situation--nay, every moment--is of infinite worth; for it is the representative of a whole eternity.',
      'In happy ignorance, I sighed for a world I did not know, where I hoped to find every pleasure and enjoyment which my heart could desire; and now, on my return from that wide world... how many disappointed hopes and unsuccessful plans have I brought back!',
      'How often do I lull my seething blood to rest, for you have never seen anything so unsteady, so uncertain, as this heart.',
      'I treat my heart like a sick child and gratify its every fancy.',
      'Oblivion is full of people who allow the opinions of others to overrule their belief in themselves.',
      'What a torment it is to see so much loveliness passing and repassing before us, and yet not dare to lay hold of it!',
      'He who cannot draw on three thousand years is living from hand to mouth.',
      'What I possess, seems far away to me, and what is gone becomes reality.',
      'Be above it! Make the world serve your purpose, but do not serve it!',
      'Every day I observe more and more the folly of judging of others by ourselves; and I have so much trouble with myself, and my own heart is in such constant agitation, that I am well content to let others pursue their own course, if they only allow me the same privilege.',
      'The highest goal that man can achieve is amazement.',
    ],
    books: [],
  },
  {
    id: 11,
    name: 'Lucius Annaeus Seneca',
    photo:
      'https://www.citatum.hu/kepek/szerzok/nagy/seneca_lucius_annaeus.jpg',
    born_date: null,
    death_date: null,
    nationality: 'Hispano-Roman',
    era: 'Hellenistic Philosophy',
    school: ['Stoicism'],
    ideas: [
      'All cruelty springs from weakness.',
      'Religion is regarded by the common people as true, by the wise as false, and by rulers as useful.',
      'There is no easy way from the earth to the stars',
      'Difficulties strengthen the mind, as labor does the body.',
      'As far as I am concerned, I know that I have lost not wealth but distractions. The body’s needs are few: it wants to be free from cold, to banish hunger and thirst with nourishment; if we long for anything more we are exerting ourselves to serve our vices, not our needs.',
      'Of all people only those are at leisure who make time for philosophy, only those are really alive. For they not only keep a good watch over their own lifetimes, but they annex every age to theirs.',
      'Men do not care how nobly they live, but only for how long, although it is within the reach of every man to live nobly, but within no man’s power to live long.',
      'We must go for walks out of doors, so that the mind can be strengthened and invigorated by a clear sky and plenty of fresh air. At times it will acquire fresh energy from a journey by carriage and a change of scene, or from socializing and drinking freely. Occasionally we should even come to the point of intoxication, sinking into drink but not being totally flooded by it; for it does wash away cares, and stirs the mind to its depths, and heals sorrow just as it heals certain diseases.',
      'What fortune has made yours is not your own.',
      'No man is more unhappy than he who never faces adversity. For he is not permitted to prove himself',
      'Hang on to your youthful enthusiasms -- you’ll be able to use them better when you’re older.',
      'The time will come when diligent research over long periods will bring to light things which now lie hidden. A single lifetime, even though entirely devoted to the sky, would not be enough for the investigation of so vast a subject... And so this knowledge will be unfolded only through long successive ages. There will come a time when our descendants will be amazed that we did not know things that are so plain to them... Many discoveries are reserved for ages still to come, when memory of us will have been effaced.',
      'If a man knows not to which port he sails, no wind is favorable.',
      'It is not that we have so little time but that we lose so much. ... The life we receive is not short but we make it so; we are not ill provided but use what we have wastefully.',
      'It is not the man who has too little, but the man who craves more, that is poor.',
      'Begin at once to live, and count each separate day as a separate life.',
      'He who is brave is free',
      'What need is there to weep over parts of life? The whole of it calls for tears.',
      'No man was ever wise by chance',
      'Associate with people who are likely to improve you.',
      'He suffers more than necessary, who suffers before it is necessary.',
      'I shall never be ashamed of citing a bad author if the line is good.',
      'Most powerful is he who has himself in his own power.',
      'Enjoy present pleasures in such a way as not to injure future ones.',
      'Wealth is the slave of a wise man. The master of a fool',
      'For what prevents us from saying that the happy life is to have a mind that is free, lofty, fearless and steadfast - a mind that is placed beyond the reach of fear, beyond the reach of desire, that counts virtue the only good, baseness the only evil, and all else but a worthless mass of things, which come and go without increasing or diminishing the highest good, and neither subtract any part from the happy life nor add any part to it? A man thus grounded must, whether he wills or not, necessarily be attended by constant cheerfulness and a joy that is deep and issues from deep within, since he finds delight in his own resources, and desires no joys greater than his inner joys.',
      'As long as you live, keep learning how to live.',
      'It is the power of the mind to be unconquerable.',
      'If you really want to escape the things that harass you, what you’re needing is not to be in a different place but to be a different person.',
      "Until we have begun to go without them, we fail to realize how unnecessary many things are. We've been using them not because we needed them but because we had them.",
      'They lose the day in expectation of the night, and the night in fear of the dawn.',
      'Only time can heal what reason cannot.',
      'Ignorance is the cause of fear.',
      "Putting things off is the biggest waste of life: it snatches away each day as it comes, and denies us the present by promising the future. The greatest obstacle to living is expectancy, which hangs upon tomorrow, and loses today. You are arranging what lies in Fortune's control, and abandoning what lies in yours. What are you looking at? To what goal are you straining? The whole future lies in uncertainty: live immediately.",
      "Life is like a play: it's not the length, but the excellence of the acting that matters.",
      'If you live in harmony with nature you will never be poor; if you live according what others think, you will never be rich.',
      'People are frugal in guarding their personal property; but as soon as it comes to squandering time they are most wasteful of the one thing in which it is right to be stingy.',
      'The sun also shines on the wicked.',
      "A sword never kills anybody; it is a tool in the killer's hand.",
      "Every new beginning comes from some other beginning's end.",
      'Often a very old man has no other proof of his long life than his age.',
      'We should every night call ourselves to an account;\r\nWhat infirmity have I mastered today?\r\nWhat passions opposed? What temptation resisted? What virtue acquired? Our vices will abort of themselves if they be brought every day to the shrift.',
      'to err is human, but to persist (in the mistake) is diabolical.',
      'There is no genius without a touch of madness.',
      'I am not born for one corner; the whole world is my native land.',
      'While we wait for life, life passes.',
      'But life is very short and anxious for those who forget the past, neglect the present, and fear the future.',
      'Fate leads the willing and drags along the reluctant.',
      'Leisure without books is death, and burial of a man alive.',
      'We learn not in the school, but in life.',
      'A gift consists not in what is done or given, but in the intention of the giver or doer.',
      'Anger, if not restrained, is frequently more hurtful to us than the injury that provokes it.',
      'Life is long if you know how to use it.',
      'Nothing is more honorable than a grateful heart.',
      'To wish to be well is a part of becoming well.',
      'It does not matter how many books you have, but how good the books are which you have.',
      'It is difficult to bring people to goodness with lessons, but it is easy to do so by example.',
      'He who spares the wicked injures the good.',
      'Fire tests gold, suffering tests brave men.',
      "It's not because things are difficult that we dare not venture. It's because we dare not venture that they are difficult.",
      "What man\r\ncan you show me who places any value on his time, who reckons the worth of each day, who understands that he is\r\ndying daily? For we are mistaken when we look forward to death; the major portion of death has already passed,\r\nWhatever years be behind us are in death's hands.",
      'It is more civilized to make fun of life than to bewail it',
      'To win true freeedom you must be a slave to philosophy.',
      'True happiness is to understand our duties toward God and man; to enjoy the present, without anxious dependence on the future; not to amuse ourselves with either hopes or fears, but to rest satisfied with what we have, which is abundantly sufficient.',
      'Nothing, to my way of thinking, is a better proof of a well ordered mind than a man’s ability to stop just where he is and pass some time in his own company.',
      'Whatever can happen at any time can happen today.',
      'But when you are looking on anyone as a friend when you do not trust him as you trust yourself, you are making a grave mistake, and have failed to grasp sufficiently the full force of true friendship.',
      'The best ideas are common property',
      'We cease to be so angry once we cease to be so hopeful',
      'Everyone prefers belief to the exercise of judgement.',
      'It is quality rather than quantity that matters.',
      'There is no enjoying the possession of anything valuable unless one has someone to share it with',
      'The final hour when we cease to exist does not itself bring death; it merely of itself completes the death-process. We reach death at that moment, but we have been a long time on the way.',
      'If we could be satisfied with anything, we should have been satisfied long ago.',
      'You live as if you were destined to live forever, no thought of your frailty ever enters your head, of how much time has already gone by you take no heed. You squander time as if you drew from a full and abundant supply, though all the while that day which you bestow on some person or thing is perhaps your last.',
      'Withdraw into yourself, as far as you can. Associate with those who will make a better man of you. Welcome those whom you yourself can improve. The process is mutual; for men learn while they teach.',
      'If anyone says that the best life of all is to sail the sea, and then adds that I must not sail upon a sea where shipwrecks are a common occurrence and there are often sudden storms that sweep the helmsman in an adverse direction, I conclude that this man, although he lauds navigation, really forbids me to launch my ship.',
      'It is a rough road that leads to the heights of greatness.',
      'Limiting one’s desires actually helps to cure one of fear. ‘Cease to hope … and you will cease to fear.’ … Widely different [as fear and hope] are, the two of them march in unison like a prisoner and the escort he is handcuffed to. Fear keeps pace with hope … both belong to a mind in suspense, to a mind in a state of anxiety through looking into the future. Both are mainly due to projecting our thoughts far ahead of us instead of adapting ourselves to the present.',
      'He who has injured thee was either stronger or weaker than thee. If weaker, spare him; if stronger, spare thyself.',
      'It is not that we have a short time to live, but that we waste a lot of it. Life is long enough, and a sufficiently generous amount has been given to us for the highest achievements if it were all well invested. But when it is wasted in heedless luxury and spent on no good activity, we are forced at last by death’s final constraint to realize that it has passed away before we knew it was passing. So it is: we are not given a short life but we make it short, and we are not ill-supplied but wasteful of it… Life is long if you know how to use it.',
      'You should … live in such a way that there is nothing which you could not as easily tell your enemy as keep to yourself.',
      "Nothing is burdensome if taken lightly, and nothing need arouse one's irritation so long as one doesn't make it bigger than it is by getting irritated.",
      "The part of life we really live is small.' For all the rest of existence is not life, but merely time.",
      'The mind that is anxious about future events is miserable.',
      'To be always fortunate, and to pass through life with a soul that has never known sorrow, is to be ignorant of one half of nature.',
      'Beyond all things is the sea',
      'Of this one thing make sure against your dying day - that your faults die before you do.',
      'No man is crushed by misfortune unless he has first been deceived by prosperity',
      'What is harder than rock? What is softer than water? Yet hard rocks are hollowed out by soft water?',
      'Light griefs are loquacious, but the great are dumb.',
      'To be everywhere is to be nowhere.',
      'When a person spends all his time in foreign travel, he ends by having many acquaintances, but no friends.',
      'Sometimes even to live is an act of courage.',
      'True happiness is to enjoy the present, without anxious dependence upon the future, not to amuse ourselves with either hopes or fears but to rest satisfied with what we have, which is sufficient, for he that is so wants nothing. The greatest blessings of mankind are within us and within our reach. A wise man is content with his lot, whatever it may be, without wishing for what he has not.',
      'Luck is what happens when preparation meets opportunity.',
      'We suffer more often in imagination than in reality',
      'You act like mortals in all that you fear, and like immortals in all that you desire',
      'As is a tale, so is life: not how long it is, but how good it is, is what matters.',
      'Philosophy calls for simple living, not for doing penance, and the simple way of life need not be a crude one.',
      'Wherever there is a human being, there is an opportunity for crisis.',
      'For many men, the acquisition of wealth does not end their troubles, it only changes them',
      'We are mad, not only individually but nationally. We check manslaughter and isolated murders, but what of war and the much-vaunted crime of slaughtering whole peoples?',
      "It's not that we have little time, but more that we waste a good deal of it.",
      'The difficulty comes from our lack of confidence.',
      'What really ruins our character is the fact that none of us looks back over his life.',
      'Drunkenness is nothing but voluntary madness',
      'Brave men rejoice in adversity, just as brave soldiers triumph in war.',
      'I have learned to be a friend to myself Great improvement this indeed Such a one can never be said to be alone for know that he who is a friend to himself is a friend to all mankind',
    ],
    books: [],
  },
  {
    id: 12,
    name: 'François-Marie Arouet (Voltaire)',
    photo:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Nicolas_de_Largilli%C3%A8re%2C_Fran%C3%A7ois-Marie_Arouet_dit_Voltaire_adjusted.png/477px-Nicolas_de_Largilli%C3%A8re%2C_Fran%C3%A7ois-Marie_Arouet_dit_Voltaire_adjusted.png',
    born_date: '1694-11-21',
    death_date: '1778-05-30',
    nationality: 'French',
    era: 'Age of Enlightenment',
    school: ['Lumières', 'Philosophes', 'Deism', 'Classical Liberalism'],
    ideas: [
      'To succeed in the world it is not enough to be stupid - one must also be polite.',
      'I would rather obey a fine lion, much stronger than myself, than two hundred rats of my own species.',
      'Meditation is the dissolution of thoughts in Eternal awareness or Pure consciousness without objectification, knowing without thinking, merging finitude in infinity.',
      'We are rarely proud when we are alone.',
      'Injustice in the end produces independence.',
      'Madness is to think of too many things in succession too fast, or of one thing too exclusively.',
      'When it is a question of money, everybody is of the same religion.',
      'Opinions have caused more ills than the plague or earthquakes on this little globe of ours.',
      'If you have two religions in your land, the two will cut each other’s throats; but if you have thirty religions, they will dwell in peace',
      'Minds differ still more than faces.',
      'It is not inequality which is the real misfortune, it is dependence.',
      'Let us read, and let us dance; these two amusements will never do any harm to the world.',
      'Life is a shipwreck, but we must not forget to sing in the lifeboats',
      'It is forbidden to kill; therefore all murderers are punished unless they kill in large numbers and to the sound of trumpets',
      'Those who can make you believe absurdities, can make you commit atrocities.',
      'Love truth, but pardon error.',
      'I have wanted to kill myself a hundred times, but somehow I am still in love with life. This ridiculous weakness is perhaps one of our more stupid melancholy propensities, for is there anything more stupid than to be eager to go on carrying a burden which one would gladly throw away, to loathe one’s very being and yet to hold it fast, to fondle the snake that devours us until it has eaten our hearts away?',
      'I have never made but one prayer to God, a very short one: Oh Lord, make my enemies ridiculous. And God granted it.',
      'God is a comedian playing to an audience that is too afraid to laugh.',
      'Every man is guilty of all the good he did not do.',
      'Despite the enormous quantity of books, how few people read! And if one reads profitably, one would realize how much stupid stuff the vulgar herd is content to swallow every day.',
      'The most important decision you make is to be in a good mood.',
      'It is better to risk saving a guilty person than to condemn an innocent one.',
      'Think for yourself and let others enjoy the privilege of doing so too.',
      'Faith consists in believing what reason cannot.',
      'Appreciation is a wonderful thing. It makes what is excellent in others belong to us as well.',
      'Our wretched species is so made that those who walk on the well-trodden path always throw stones at those who are showing a new road.',
      'The human brain is a complex organ with the wonderful power of enabling man to find reasons for continuing to believe whatever it is that he wants to believe.',
      'Let us cultivate our garden.',
      'The comfort of the rich depends upon an abundant supply of the poor.',
      'What is history? The lie that everyone agrees on...',
      'The art of medicine consists of amusing the patient while nature cures the disease.',
      'It is not enough to conquer; one must learn to seduce.',
      'Men will always be mad, and those who think they can cure them are the maddest of all.',
      'Man is free at the instant he wants to be.',
      'Judge a man by his questions rather than by his answers.',
      'The more I read, the more I acquire, the more certain I am that I know nothing.',
      'Common sense is not so common.',
      'I don’t know where I am going, but I am on my way',
      'Fools have a habit of believing that everything written by a famous author is admirable. For my part I read only to please myself and like only what suits my taste.',
      'Dare to think for yourself.',
      'It is dangerous to be right in matters on which the established authorities are wrong.',
      'God is a circle whose center is everywhere and circumference nowhere.',
      'The secret of being a bore is to tell everything.',
      'Doubt is an uncomfortable condition, but certainty is a ridiculous one.',
      'Cherish those who seek the truth but beware of those who find it.',
      'Every man is a creature of the age in which he lives and few are able to raise themselves above the ideas of the time.',
      'If God did not exist, it would be necessary to invent him.',
      'Prejudices are what fools use for reason.',
      'We never live; we are always in the expectation of living.',
      "Don't think money does everything or you are going to end up doing everything for money.",
      'No opinion is worth burning your neighbor for.',
      'The discovery of what is true and the practice of that which is good are the two most important aims of philosophy.',
      'Men argue. Nature acts.',
      'Martin in particular concluded that man was born to live either in the convulsions of misery, or in the lethargy of boredom.',
      'Is politics nothing other than the art of deliberately lying?',
      'There is a wide difference between speaking to deceive, and being silent to be impenetrable.',
      'Answer me, you who believe that animals are only machines. Has nature arranged for this animal to have all the machinery of feelings only in order for it not to have any at all?',
      'The greatest consolation in life is to say what one thinks.',
      'It is love; love, the comfort of the human species, the preserver of the universe, the soul of all sentient beings, love, tender love.',
      'There are truths which are not for all men, nor for all times.',
      'No problem can stand the assault of sustained thinking.',
      'Religion began when the first scoundrel met the first fool.',
      'Sensual pleasure passes and vanishes, but the friendship between us, the mutual confidence, the delight of the heart, the enchantment of the soul, these things do not perish and can never be destroyed.',
      'If we do not find anything very pleasant, at least we shall find something new.',
      'In general, the art of government consists in taking as much money as possible from one party of the citizens to give to the other.',
      'Reading nurtures the soul, and an enlightened friend brings it solace.',
      'Being unable to make people more reasonable, I preferred to be happy away from them',
      'Four thousand volumes of metaphysics will not teach us what the soul is.',
      'I have chosen to be happy because it is good for my health.',
      'If there’s life on other planets, then the earth is the Universe’s insane asylum.',
      'Fools admire everything in an author of reputation.',
      'Love is a canvas furnished by Nature and embroidered by imagination.',
      'I know many books which have bored their readers, but I know of none which has done real evil.',
      'It is not more surprising to be born twice than once; everything in nature is resurrection.',
      'Men use thought only as authority for their injustice, and employ speech only to conceal their thoughts.',
      'Beware of the words "internal security," for they are the eternal cry of the oppressor.',
      'To the living we owe respect, but to the dead we owe only the truth.',
      'Discord is the great ill of mankind; and tolerance is the only remedy for it.',
      'We all look for happiness, but without knowing where to find it: like drunkards who look for their house, knowing dimly that they have one',
      'I hold firmly to my original views. After all I am a philosopher.',
      'One always begins with the simple, then comes the complex, and by superior enlightenment one often reverts in the end to the simple. Such is the course of human intelligence.',
      'God gave us the gift of life; it is up to us to give ourselves the gift of living well.',
      'But for what purpose was the earth formed?" asked Candide. "To drive us mad," replied Martin',
      'It is clear that the individual who persecutes a man, his brother, because he is not of the same opinion, is a monster.',
      '“What a pessimist you are!" exclaimed Candide.\r\n"That is because I know what life is," said Martin.”',
      'This agglomeration which was called and which still calls itself the Holy Roman Empire was neither holy, nor Roman, nor an empire.',
      'Whatever you do, crush the infamous thing, and love those who love you.',
      'Of all religions, the Christian should of course inspire the most tolerance, but until now Christians have been the most intolerant of all men.',
      'He wanted to know how they prayed to God in El Dorado. "We do not pray to him at all," said the reverend sage. "We have nothing to ask of him. He has given us all we want, and we give him thanks continually.',
      'If this is the best of possible worlds, what then are the others?',
      'Animals have these advantages over man: they never hear the clock strike, they die without any idea of death, they have no theologians to instruct them, their last moments are not disturbed by unwelcome and unpleasant ceremonies, their funerals cost them nothing, and no one starts lawsuits over their wills.',
      'Perfect is the enemy of good.',
      'The longer we dwell on our misfortunes, the greater is their power to harm us',
      'It is with books as with men: a very small number play a great part.',
      'Liberty of thought is the life of the soul.',
      'The only way to comprehend what mathematicians mean by Infinity is to contemplate the extent of human stupidity.',
      'Our labour preserves us from three great evils -- weariness, vice, and want.',
      "One day everything will be well, that is our hope. Everything's fine today, that is our illusion",
      'He must be very ignorant for he answers every question he is asked.',
      'The happiest of all lives is a busy solitude.',
      'Men are equal; it is not birth but virtue that makes the difference.',
      'History never repeats itself. Man always does.',
      'It is an infantile superstition of the human spirit that virginity would be thought a virtue and not the barrier that separates ignorance from knowledge.',
      "Do you believe,' said Candide, 'that men have always massacred each other as they do to-day, that they have always been liars, cheats, traitors, ingrates, brigands, idiots, thieves, scoundrels, gluttons, drunkards, misers, envious, ambitious, bloody-minded, calumniators, debauchees, fanatics, hypocrites, and fools?'\r\nDo you believe,' said Martin, 'that hawks have always eaten pigeons when they have found them?",
      'May God defend me from my friends: I can defend myself from my enemies.',
      'I loved him as we always love for the first time; with idolatry and wild passion.',
      'She blushed and so did he. She greeted him in a faltering voice, and he spoke to her without knowing what he was saying.',
      'Behind every successful man stands a surprised mother-in-law.',
      'One great use of words is to hide our thoughts.',
      'To hold a pen is to be at war.',
      "What can you say to a man who tells you he prefers obeying God rather than men, and that as a result he's certain he'll go to heaven if he cuts your throat?",
      'It is hard to free fools from the chains they revere.',
      'When a man is in love, jealous, and just whipped by the Inquisition, he is no longer himself.',
      'Each player must accept the cards life deals him or her; but once they are in hand, he or she alone must decide how to play the cards in order to win the game.',
      'In every province, the chief occupations, in order of importance, are lovemaking, malicious gossip, and talking nonsense.',
      'Doctors put drugs of which they know little into bodies of which they know less for diseases of which they know nothing at all',
      'Come! you presence will either give me life or kill me with pleasure.',
      'The more a man knows, the less he talks.',
    ],
    books: [],
  },
];
